// <auto-generated />
using System;
using ArckDan.MayDay.Repositorio.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArckDan.MayDay.Repositorio.Migrations
{
    [DbContext(typeof(MayDayContext))]
    [Migration("20220119183357_MayDay0001")]
    partial class MayDay0001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Acesso.LoginModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<DateTime>("Inclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.ToTable("TB_MAYDAY_LOGIN");
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Acesso.SenhaModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("CHAVE");

                    b.Property<DateTime>("Expiracao")
                        .HasColumnType("datetime")
                        .HasColumnName("EXPIRACAO");

                    b.Property<int>("IdLogin")
                        .HasColumnType("int")
                        .HasColumnName("ID_LOGIN");

                    b.Property<DateTime>("Inclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_INCLUSAO");

                    b.HasKey("Id");

                    b.HasIndex("IdLogin");

                    b.ToTable("TB_MAYDAY_SENHA");
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Acesso.TokenModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<DateTime>("Inclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("SENHA");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.ToTable("TB_MAYDAY_TOKEN");
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Operacional.CampoModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTime>("Inclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NOME");

                    b.Property<string>("NomeTecnico")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("NOME_TECNICO");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int")
                        .HasColumnName("TAMANHO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.ToTable("TB_MAYDAY_CAMPO");
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Operacional.EnderecoModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    b.Property<DateTime>("Inclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<int>("Numero")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("UF");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_MAYDAY_ENDERECO");
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Operacional.PerfilModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTime>("Inclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("TB_MAYDAY_PERFIL");
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Operacional.UsuarioModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_ALTERACAO");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("CPF");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int")
                        .HasColumnName("ID_PERFIL");

                    b.Property<DateTime>("Inclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_INCLUSAO");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.ToTable("TB_MAYDAY_USUARIO");
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Relacional.CampoPerfilModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("IdCampo")
                        .HasColumnType("int")
                        .HasColumnName("ID_CAMPO");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int")
                        .HasColumnName("ID_PERFIL");

                    b.HasKey("Id");

                    b.HasIndex("IdCampo");

                    b.HasIndex("IdPerfil");

                    b.ToTable("TB_MAYDAY_CAMPO_PERFIL");
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Acesso.SenhaModel", b =>
                {
                    b.HasOne("ArckDan.MayDay.Domain.Models.Acesso.LoginModel", null)
                        .WithMany("Senha")
                        .HasForeignKey("IdLogin")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Operacional.EnderecoModel", b =>
                {
                    b.HasOne("ArckDan.MayDay.Domain.Models.Operacional.UsuarioModel", null)
                        .WithMany("Endereco")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Operacional.UsuarioModel", b =>
                {
                    b.HasOne("ArckDan.MayDay.Domain.Models.Operacional.PerfilModel", null)
                        .WithMany("Usuario")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Relacional.CampoPerfilModel", b =>
                {
                    b.HasOne("ArckDan.MayDay.Domain.Models.Operacional.CampoModel", null)
                        .WithMany("Campo")
                        .HasForeignKey("IdCampo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ArckDan.MayDay.Domain.Models.Operacional.PerfilModel", null)
                        .WithMany("Perfil")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Acesso.LoginModel", b =>
                {
                    b.Navigation("Senha");
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Operacional.CampoModel", b =>
                {
                    b.Navigation("Campo");
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Operacional.PerfilModel", b =>
                {
                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArckDan.MayDay.Domain.Models.Operacional.UsuarioModel", b =>
                {
                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
